version: '3.7'

networks:
  traefik-proxy:
    external: true
  # webshop-network:

services:
  frontend:
    image: anderszobbesoftware/casa-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.Casazayfront.rule=Host(`casa.kubelab.dk`)"
          - "traefik.http.routers.Casazayfront.entrypoints=web,websecure"
          - "traefik.http.routers.Casazayfront.tls.certresolver=letsencrypt"
          - "traefik.http.services.Casazayfront.loadbalancer.server.port=8080"
    
    restart: unless-stopped
    networks:
      - traefik-proxy

  backend:
    image: anderszobbesoftware/casa-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.CasazayBack.rule=Host(`casaadmin.kubelab.dk`)"
          - "traefik.http.routers.CasazayBack.entrypoints=web,websecure"
          - "traefik.http.routers.CasazayBack.tls.certresolver=letsencrypt"
          - "traefik.http.services.CasazayBack.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy
    restart: unless-stopped
    environment:
      DB_PORT: 3306
      DB_HOSTNAME: zay-ecormmerce-db.mysql.database.azure.com
      DB_USERNAME: Casaroot
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: zay
    command: sh -c "npm start"

